services:
  custom_verifier_frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_URL=https://verifierapi.openid4vc.staging.yivi.app
      - VERAMO_API_URL=https://veramo-verifier.openid4vc.staging.yivi.app
      - VERAMO_VERIFIER_NAME=test-verifier
      - VERAMO_ADMIN_TOKEN=test-verifier-admin-token
