export VITE_API_URL=$API_URL
export VITE_VERAMO_API_URL=$VERAMO_API_URL
export VITE_VERAMO_VERIFIER_NAME=$VERAMO_VERIFIER_NAME
export VITE_VERAMO_ADMIN_TOKEN=$VERAMO_ADMIN_TOKEN
npm run dev -- --host $HOST --port $PORT
